// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/passkeper.proto

package pkppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_UNSPECIFIED ItemType = 0
	ItemType_CREDENTIAL  ItemType = 1
	ItemType_TEXT        ItemType = 2
	ItemType_BINARY      ItemType = 3
	ItemType_CARD        ItemType = 4
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREDENTIAL",
		2: "TEXT",
		3: "BINARY",
		4: "CARD",
	}
	ItemType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CREDENTIAL":  1,
		"TEXT":        2,
		"BINARY":      3,
		"CARD":        4,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_passkeper_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_pkg_api_passkeper_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLogin     string                 `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	UserPassword  string                 `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{3}
}

func (x *Credentials) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *Credentials) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *Credentials) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{4}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Binary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{5}
}

func (x *Binary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Binary) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Exp           string                 `protobuf:"bytes,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{6}
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *Card) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *Card) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ItemData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ItemData_Credentials
	//	*ItemData_Text
	//	*ItemData_Binary
	//	*ItemData_Card
	Data          isItemData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{7}
}

func (x *ItemData) GetData() isItemData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ItemData) GetCredentials() *Credentials {
	if x != nil {
		if x, ok := x.Data.(*ItemData_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *ItemData) GetText() *Text {
	if x != nil {
		if x, ok := x.Data.(*ItemData_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ItemData) GetBinary() *Binary {
	if x != nil {
		if x, ok := x.Data.(*ItemData_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *ItemData) GetCard() *Card {
	if x != nil {
		if x, ok := x.Data.(*ItemData_Card); ok {
			return x.Card
		}
	}
	return nil
}

type isItemData_Data interface {
	isItemData_Data()
}

type ItemData_Credentials struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3,oneof"`
}

type ItemData_Text struct {
	Text *Text `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type ItemData_Binary struct {
	Binary *Binary `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

type ItemData_Card struct {
	Card *Card `protobuf:"bytes,4,opt,name=card,proto3,oneof"`
}

func (*ItemData_Credentials) isItemData_Data() {}

func (*ItemData_Text) isItemData_Data() {}

func (*ItemData_Binary) isItemData_Data() {}

func (*ItemData_Card) isItemData_Data() {}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=passkeeper.ItemType" json:"type,omitempty"`
	Data          *ItemData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{8}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_UNSPECIFIED
}

func (x *Item) GetData() *ItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ItemType               `protobuf:"varint,1,opt,name=type,proto3,enum=passkeeper.ItemType" json:"type,omitempty"`
	Data          *ItemData              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{9}
}

func (x *CreateItemRequest) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_UNSPECIFIED
}

func (x *CreateItemRequest) GetData() *ItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{10}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=passkeeper.ItemType" json:"type,omitempty"`
	Data          *ItemData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_UNSPECIFIED
}

func (x *UpdateItemRequest) GetData() *ItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateItemRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{14}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{15}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ItemType               `protobuf:"varint,1,opt,name=type,proto3,enum=passkeeper.ItemType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{16}
}

func (x *ListItemsRequest) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_UNSPECIFIED
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_pkg_api_passkeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_passkeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_passkeper_proto_rawDescGZIP(), []int{17}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_api_passkeper_proto protoreflect.FileDescriptor

const file_pkg_api_passkeper_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/passkeper.proto\x12\n" +
	"passkeeper\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"m\n" +
	"\vCredentials\x12\x1d\n" +
	"\n" +
	"user_login\x18\x01 \x01(\tR\tuserLogin\x12#\n" +
	"\ruser_password\x18\x02 \x01(\tR\fuserPassword\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"6\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"8\n" +
	"\x06Binary\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"r\n" +
	"\x04Card\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\xcd\x01\n" +
	"\bItemData\x12;\n" +
	"\vcredentials\x18\x01 \x01(\v2\x17.passkeeper.CredentialsH\x00R\vcredentials\x12&\n" +
	"\x04text\x18\x02 \x01(\v2\x10.passkeeper.TextH\x00R\x04text\x12,\n" +
	"\x06binary\x18\x03 \x01(\v2\x12.passkeeper.BinaryH\x00R\x06binary\x12&\n" +
	"\x04card\x18\x04 \x01(\v2\x10.passkeeper.CardH\x00R\x04cardB\x06\n" +
	"\x04data\"\xe0\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.passkeeper.ItemTypeR\x04type\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.passkeeper.ItemDataR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"g\n" +
	"\x11CreateItemRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.passkeeper.ItemTypeR\x04type\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.passkeeper.ItemDataR\x04data\":\n" +
	"\x12CreateItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.passkeeper.ItemR\x04item\"\xb2\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.passkeeper.ItemTypeR\x04type\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.passkeeper.ItemDataR\x04data\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x12UpdateItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.passkeeper.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fGetItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.passkeeper.ItemR\x04item\"<\n" +
	"\x10ListItemsRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.passkeeper.ItemTypeR\x04type\";\n" +
	"\x11ListItemsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.passkeeper.ItemR\x05items*K\n" +
	"\bItemType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CREDENTIAL\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\n" +
	"\n" +
	"\x06BINARY\x10\x03\x12\b\n" +
	"\x04CARD\x10\x042\x96\x01\n" +
	"\x15PasskeeperAuthService\x12?\n" +
	"\bRegister\x12\x1b.passkeeper.RegisterRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\x05Login\x12\x18.passkeeper.LoginRequest\x1a\x19.passkeeper.LoginResponse2\x84\x03\n" +
	"\x15PasskeeperItemService\x12K\n" +
	"\n" +
	"CreateItem\x12\x1d.passkeeper.CreateItemRequest\x1a\x1e.passkeeper.CreateItemResponse\x12K\n" +
	"\n" +
	"UpdateItem\x12\x1d.passkeeper.UpdateItemRequest\x1a\x1e.passkeeper.UpdateItemResponse\x12C\n" +
	"\n" +
	"DeleteItem\x12\x1d.passkeeper.DeleteItemRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\aGetItem\x12\x1a.passkeeper.GetItemRequest\x1a\x1b.passkeeper.GetItemResponse\x12H\n" +
	"\tListItems\x12\x1c.passkeeper.ListItemsRequest\x1a\x1d.passkeeper.ListItemsResponseB2Z0github.com/devize-ed/passKeper.git/pkg/api;pkppbb\x06proto3"

var (
	file_pkg_api_passkeper_proto_rawDescOnce sync.Once
	file_pkg_api_passkeper_proto_rawDescData []byte
)

func file_pkg_api_passkeper_proto_rawDescGZIP() []byte {
	file_pkg_api_passkeper_proto_rawDescOnce.Do(func() {
		file_pkg_api_passkeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_passkeper_proto_rawDesc), len(file_pkg_api_passkeper_proto_rawDesc)))
	})
	return file_pkg_api_passkeper_proto_rawDescData
}

var file_pkg_api_passkeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_passkeper_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_api_passkeper_proto_goTypes = []any{
	(ItemType)(0),                 // 0: passkeeper.ItemType
	(*RegisterRequest)(nil),       // 1: passkeeper.RegisterRequest
	(*LoginRequest)(nil),          // 2: passkeeper.LoginRequest
	(*LoginResponse)(nil),         // 3: passkeeper.LoginResponse
	(*Credentials)(nil),           // 4: passkeeper.Credentials
	(*Text)(nil),                  // 5: passkeeper.Text
	(*Binary)(nil),                // 6: passkeeper.Binary
	(*Card)(nil),                  // 7: passkeeper.Card
	(*ItemData)(nil),              // 8: passkeeper.ItemData
	(*Item)(nil),                  // 9: passkeeper.Item
	(*CreateItemRequest)(nil),     // 10: passkeeper.CreateItemRequest
	(*CreateItemResponse)(nil),    // 11: passkeeper.CreateItemResponse
	(*UpdateItemRequest)(nil),     // 12: passkeeper.UpdateItemRequest
	(*UpdateItemResponse)(nil),    // 13: passkeeper.UpdateItemResponse
	(*DeleteItemRequest)(nil),     // 14: passkeeper.DeleteItemRequest
	(*GetItemRequest)(nil),        // 15: passkeeper.GetItemRequest
	(*GetItemResponse)(nil),       // 16: passkeeper.GetItemResponse
	(*ListItemsRequest)(nil),      // 17: passkeeper.ListItemsRequest
	(*ListItemsResponse)(nil),     // 18: passkeeper.ListItemsResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_pkg_api_passkeper_proto_depIdxs = []int32{
	4,  // 0: passkeeper.ItemData.credentials:type_name -> passkeeper.Credentials
	5,  // 1: passkeeper.ItemData.text:type_name -> passkeeper.Text
	6,  // 2: passkeeper.ItemData.binary:type_name -> passkeeper.Binary
	7,  // 3: passkeeper.ItemData.card:type_name -> passkeeper.Card
	0,  // 4: passkeeper.Item.type:type_name -> passkeeper.ItemType
	8,  // 5: passkeeper.Item.data:type_name -> passkeeper.ItemData
	19, // 6: passkeeper.Item.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: passkeeper.Item.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: passkeeper.CreateItemRequest.type:type_name -> passkeeper.ItemType
	8,  // 9: passkeeper.CreateItemRequest.data:type_name -> passkeeper.ItemData
	9,  // 10: passkeeper.CreateItemResponse.item:type_name -> passkeeper.Item
	0,  // 11: passkeeper.UpdateItemRequest.type:type_name -> passkeeper.ItemType
	8,  // 12: passkeeper.UpdateItemRequest.data:type_name -> passkeeper.ItemData
	19, // 13: passkeeper.UpdateItemRequest.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 14: passkeeper.UpdateItemResponse.item:type_name -> passkeeper.Item
	9,  // 15: passkeeper.GetItemResponse.item:type_name -> passkeeper.Item
	0,  // 16: passkeeper.ListItemsRequest.type:type_name -> passkeeper.ItemType
	9,  // 17: passkeeper.ListItemsResponse.items:type_name -> passkeeper.Item
	1,  // 18: passkeeper.PasskeeperAuthService.Register:input_type -> passkeeper.RegisterRequest
	2,  // 19: passkeeper.PasskeeperAuthService.Login:input_type -> passkeeper.LoginRequest
	10, // 20: passkeeper.PasskeeperItemService.CreateItem:input_type -> passkeeper.CreateItemRequest
	12, // 21: passkeeper.PasskeeperItemService.UpdateItem:input_type -> passkeeper.UpdateItemRequest
	14, // 22: passkeeper.PasskeeperItemService.DeleteItem:input_type -> passkeeper.DeleteItemRequest
	15, // 23: passkeeper.PasskeeperItemService.GetItem:input_type -> passkeeper.GetItemRequest
	17, // 24: passkeeper.PasskeeperItemService.ListItems:input_type -> passkeeper.ListItemsRequest
	20, // 25: passkeeper.PasskeeperAuthService.Register:output_type -> google.protobuf.Empty
	3,  // 26: passkeeper.PasskeeperAuthService.Login:output_type -> passkeeper.LoginResponse
	11, // 27: passkeeper.PasskeeperItemService.CreateItem:output_type -> passkeeper.CreateItemResponse
	13, // 28: passkeeper.PasskeeperItemService.UpdateItem:output_type -> passkeeper.UpdateItemResponse
	20, // 29: passkeeper.PasskeeperItemService.DeleteItem:output_type -> google.protobuf.Empty
	16, // 30: passkeeper.PasskeeperItemService.GetItem:output_type -> passkeeper.GetItemResponse
	18, // 31: passkeeper.PasskeeperItemService.ListItems:output_type -> passkeeper.ListItemsResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_api_passkeper_proto_init() }
func file_pkg_api_passkeper_proto_init() {
	if File_pkg_api_passkeper_proto != nil {
		return
	}
	file_pkg_api_passkeper_proto_msgTypes[7].OneofWrappers = []any{
		(*ItemData_Credentials)(nil),
		(*ItemData_Text)(nil),
		(*ItemData_Binary)(nil),
		(*ItemData_Card)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_passkeper_proto_rawDesc), len(file_pkg_api_passkeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_passkeper_proto_goTypes,
		DependencyIndexes: file_pkg_api_passkeper_proto_depIdxs,
		EnumInfos:         file_pkg_api_passkeper_proto_enumTypes,
		MessageInfos:      file_pkg_api_passkeper_proto_msgTypes,
	}.Build()
	File_pkg_api_passkeper_proto = out.File
	file_pkg_api_passkeper_proto_goTypes = nil
	file_pkg_api_passkeper_proto_depIdxs = nil
}
