// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	pkppb "passKeper/pkg/api"
)

// MockPasskeeperAuthServiceClient is an autogenerated mock type for the PasskeeperAuthServiceClient type
type MockPasskeeperAuthServiceClient struct {
	mock.Mock
}

type MockPasskeeperAuthServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasskeeperAuthServiceClient) EXPECT() *MockPasskeeperAuthServiceClient_Expecter {
	return &MockPasskeeperAuthServiceClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperAuthServiceClient) Login(ctx context.Context, in *pkppb.LoginRequest, opts ...grpc.CallOption) (*pkppb.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *pkppb.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.LoginRequest, ...grpc.CallOption) (*pkppb.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.LoginRequest, ...grpc.CallOption) *pkppb.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkppb.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperAuthServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockPasskeeperAuthServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperAuthServiceClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperAuthServiceClient_Login_Call {
	return &MockPasskeeperAuthServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperAuthServiceClient_Login_Call) Run(run func(ctx context.Context, in *pkppb.LoginRequest, opts ...grpc.CallOption)) *MockPasskeeperAuthServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperAuthServiceClient_Login_Call) Return(_a0 *pkppb.LoginResponse, _a1 error) *MockPasskeeperAuthServiceClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperAuthServiceClient_Login_Call) RunAndReturn(run func(context.Context, *pkppb.LoginRequest, ...grpc.CallOption) (*pkppb.LoginResponse, error)) *MockPasskeeperAuthServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperAuthServiceClient) Register(ctx context.Context, in *pkppb.RegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.RegisterRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.RegisterRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperAuthServiceClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockPasskeeperAuthServiceClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperAuthServiceClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperAuthServiceClient_Register_Call {
	return &MockPasskeeperAuthServiceClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperAuthServiceClient_Register_Call) Run(run func(ctx context.Context, in *pkppb.RegisterRequest, opts ...grpc.CallOption)) *MockPasskeeperAuthServiceClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.RegisterRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperAuthServiceClient_Register_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockPasskeeperAuthServiceClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperAuthServiceClient_Register_Call) RunAndReturn(run func(context.Context, *pkppb.RegisterRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *MockPasskeeperAuthServiceClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasskeeperAuthServiceClient creates a new instance of MockPasskeeperAuthServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasskeeperAuthServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasskeeperAuthServiceClient {
	mock := &MockPasskeeperAuthServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
