// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	pkppb "passKeper/pkg/api"
)

// MockPasskeeperItemServiceClient is an autogenerated mock type for the PasskeeperItemServiceClient type
type MockPasskeeperItemServiceClient struct {
	mock.Mock
}

type MockPasskeeperItemServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasskeeperItemServiceClient) EXPECT() *MockPasskeeperItemServiceClient_Expecter {
	return &MockPasskeeperItemServiceClient_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperItemServiceClient) CreateItem(ctx context.Context, in *pkppb.CreateItemRequest, opts ...grpc.CallOption) (*pkppb.CreateItemResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *pkppb.CreateItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.CreateItemRequest, ...grpc.CallOption) (*pkppb.CreateItemResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.CreateItemRequest, ...grpc.CallOption) *pkppb.CreateItemResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkppb.CreateItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.CreateItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperItemServiceClient_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockPasskeeperItemServiceClient_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.CreateItemRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperItemServiceClient_Expecter) CreateItem(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperItemServiceClient_CreateItem_Call {
	return &MockPasskeeperItemServiceClient_CreateItem_Call{Call: _e.mock.On("CreateItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperItemServiceClient_CreateItem_Call) Run(run func(ctx context.Context, in *pkppb.CreateItemRequest, opts ...grpc.CallOption)) *MockPasskeeperItemServiceClient_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.CreateItemRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperItemServiceClient_CreateItem_Call) Return(_a0 *pkppb.CreateItemResponse, _a1 error) *MockPasskeeperItemServiceClient_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperItemServiceClient_CreateItem_Call) RunAndReturn(run func(context.Context, *pkppb.CreateItemRequest, ...grpc.CallOption) (*pkppb.CreateItemResponse, error)) *MockPasskeeperItemServiceClient_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperItemServiceClient) DeleteItem(ctx context.Context, in *pkppb.DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.DeleteItemRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.DeleteItemRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.DeleteItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperItemServiceClient_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockPasskeeperItemServiceClient_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.DeleteItemRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperItemServiceClient_Expecter) DeleteItem(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperItemServiceClient_DeleteItem_Call {
	return &MockPasskeeperItemServiceClient_DeleteItem_Call{Call: _e.mock.On("DeleteItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperItemServiceClient_DeleteItem_Call) Run(run func(ctx context.Context, in *pkppb.DeleteItemRequest, opts ...grpc.CallOption)) *MockPasskeeperItemServiceClient_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.DeleteItemRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperItemServiceClient_DeleteItem_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockPasskeeperItemServiceClient_DeleteItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperItemServiceClient_DeleteItem_Call) RunAndReturn(run func(context.Context, *pkppb.DeleteItemRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *MockPasskeeperItemServiceClient_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperItemServiceClient) GetItem(ctx context.Context, in *pkppb.GetItemRequest, opts ...grpc.CallOption) (*pkppb.GetItemResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *pkppb.GetItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.GetItemRequest, ...grpc.CallOption) (*pkppb.GetItemResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.GetItemRequest, ...grpc.CallOption) *pkppb.GetItemResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkppb.GetItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.GetItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperItemServiceClient_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockPasskeeperItemServiceClient_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.GetItemRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperItemServiceClient_Expecter) GetItem(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperItemServiceClient_GetItem_Call {
	return &MockPasskeeperItemServiceClient_GetItem_Call{Call: _e.mock.On("GetItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperItemServiceClient_GetItem_Call) Run(run func(ctx context.Context, in *pkppb.GetItemRequest, opts ...grpc.CallOption)) *MockPasskeeperItemServiceClient_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.GetItemRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperItemServiceClient_GetItem_Call) Return(_a0 *pkppb.GetItemResponse, _a1 error) *MockPasskeeperItemServiceClient_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperItemServiceClient_GetItem_Call) RunAndReturn(run func(context.Context, *pkppb.GetItemRequest, ...grpc.CallOption) (*pkppb.GetItemResponse, error)) *MockPasskeeperItemServiceClient_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperItemServiceClient) ListItems(ctx context.Context, in *pkppb.ListItemsRequest, opts ...grpc.CallOption) (*pkppb.ListItemsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 *pkppb.ListItemsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.ListItemsRequest, ...grpc.CallOption) (*pkppb.ListItemsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.ListItemsRequest, ...grpc.CallOption) *pkppb.ListItemsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkppb.ListItemsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.ListItemsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperItemServiceClient_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockPasskeeperItemServiceClient_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.ListItemsRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperItemServiceClient_Expecter) ListItems(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperItemServiceClient_ListItems_Call {
	return &MockPasskeeperItemServiceClient_ListItems_Call{Call: _e.mock.On("ListItems",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperItemServiceClient_ListItems_Call) Run(run func(ctx context.Context, in *pkppb.ListItemsRequest, opts ...grpc.CallOption)) *MockPasskeeperItemServiceClient_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.ListItemsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperItemServiceClient_ListItems_Call) Return(_a0 *pkppb.ListItemsResponse, _a1 error) *MockPasskeeperItemServiceClient_ListItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperItemServiceClient_ListItems_Call) RunAndReturn(run func(context.Context, *pkppb.ListItemsRequest, ...grpc.CallOption) (*pkppb.ListItemsResponse, error)) *MockPasskeeperItemServiceClient_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, in, opts
func (_m *MockPasskeeperItemServiceClient) UpdateItem(ctx context.Context, in *pkppb.UpdateItemRequest, opts ...grpc.CallOption) (*pkppb.UpdateItemResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *pkppb.UpdateItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.UpdateItemRequest, ...grpc.CallOption) (*pkppb.UpdateItemResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pkppb.UpdateItemRequest, ...grpc.CallOption) *pkppb.UpdateItemResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkppb.UpdateItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pkppb.UpdateItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasskeeperItemServiceClient_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockPasskeeperItemServiceClient_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *pkppb.UpdateItemRequest
//   - opts ...grpc.CallOption
func (_e *MockPasskeeperItemServiceClient_Expecter) UpdateItem(ctx interface{}, in interface{}, opts ...interface{}) *MockPasskeeperItemServiceClient_UpdateItem_Call {
	return &MockPasskeeperItemServiceClient_UpdateItem_Call{Call: _e.mock.On("UpdateItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockPasskeeperItemServiceClient_UpdateItem_Call) Run(run func(ctx context.Context, in *pkppb.UpdateItemRequest, opts ...grpc.CallOption)) *MockPasskeeperItemServiceClient_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*pkppb.UpdateItemRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockPasskeeperItemServiceClient_UpdateItem_Call) Return(_a0 *pkppb.UpdateItemResponse, _a1 error) *MockPasskeeperItemServiceClient_UpdateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasskeeperItemServiceClient_UpdateItem_Call) RunAndReturn(run func(context.Context, *pkppb.UpdateItemRequest, ...grpc.CallOption) (*pkppb.UpdateItemResponse, error)) *MockPasskeeperItemServiceClient_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasskeeperItemServiceClient creates a new instance of MockPasskeeperItemServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasskeeperItemServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasskeeperItemServiceClient {
	mock := &MockPasskeeperItemServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
