// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	db "passKeper/internal/repository/db"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, userID, itemType, itemData
func (_m *MockStorage) CreateItem(ctx context.Context, userID string, itemType int32, itemData []byte) (db.Item, error) {
	ret := _m.Called(ctx, userID, itemType, itemData)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, []byte) (db.Item, error)); ok {
		return rf(ctx, userID, itemType, itemData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, []byte) db.Item); ok {
		r0 = rf(ctx, userID, itemType, itemData)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, []byte) error); ok {
		r1 = rf(ctx, userID, itemType, itemData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockStorage_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemType int32
//   - itemData []byte
func (_e *MockStorage_Expecter) CreateItem(ctx interface{}, userID interface{}, itemType interface{}, itemData interface{}) *MockStorage_CreateItem_Call {
	return &MockStorage_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, userID, itemType, itemData)}
}

func (_c *MockStorage_CreateItem_Call) Run(run func(ctx context.Context, userID string, itemType int32, itemData []byte)) *MockStorage_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].([]byte))
	})
	return _c
}

func (_c *MockStorage_CreateItem_Call) Return(_a0 db.Item, _a1 error) *MockStorage_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateItem_Call) RunAndReturn(run func(context.Context, string, int32, []byte) (db.Item, error)) *MockStorage_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, username, passwordHash
func (_m *MockStorage) CreateUser(ctx context.Context, username string, passwordHash string) error {
	ret := _m.Called(ctx, username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - passwordHash string
func (_e *MockStorage_Expecter) CreateUser(ctx interface{}, username interface{}, passwordHash interface{}) *MockStorage_CreateUser_Call {
	return &MockStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, passwordHash)}
}

func (_c *MockStorage_CreateUser_Call) Run(run func(ctx context.Context, username string, passwordHash string)) *MockStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_CreateUser_Call) Return(_a0 error) *MockStorage_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, userID, itemID
func (_m *MockStorage) DeleteItem(ctx context.Context, userID string, itemID string) error {
	ret := _m.Called(ctx, userID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockStorage_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemID string
func (_e *MockStorage_Expecter) DeleteItem(ctx interface{}, userID interface{}, itemID interface{}) *MockStorage_DeleteItem_Call {
	return &MockStorage_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, userID, itemID)}
}

func (_c *MockStorage_DeleteItem_Call) Run(run func(ctx context.Context, userID string, itemID string)) *MockStorage_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteItem_Call) Return(_a0 error) *MockStorage_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteItem_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function with given fields: ctx, userID, itemType
func (_m *MockStorage) GetAllItems(ctx context.Context, userID string, itemType int32) ([]db.Item, error) {
	ret := _m.Called(ctx, userID, itemType)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) ([]db.Item, error)); ok {
		return rf(ctx, userID, itemType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) []db.Item); ok {
		r0 = rf(ctx, userID, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = rf(ctx, userID, itemType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockStorage_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemType int32
func (_e *MockStorage_Expecter) GetAllItems(ctx interface{}, userID interface{}, itemType interface{}) *MockStorage_GetAllItems_Call {
	return &MockStorage_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx, userID, itemType)}
}

func (_c *MockStorage_GetAllItems_Call) Run(run func(ctx context.Context, userID string, itemType int32)) *MockStorage_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32))
	})
	return _c
}

func (_c *MockStorage_GetAllItems_Call) Return(_a0 []db.Item, _a1 error) *MockStorage_GetAllItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetAllItems_Call) RunAndReturn(run func(context.Context, string, int32) ([]db.Item, error)) *MockStorage_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, id, userID
func (_m *MockStorage) GetItem(ctx context.Context, id string, userID string) (db.Item, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.Item, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.Item); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockStorage_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockStorage_Expecter) GetItem(ctx interface{}, id interface{}, userID interface{}) *MockStorage_GetItem_Call {
	return &MockStorage_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id, userID)}
}

func (_c *MockStorage_GetItem_Call) Run(run func(ctx context.Context, id string, userID string)) *MockStorage_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_GetItem_Call) Return(_a0 db.Item, _a1 error) *MockStorage_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetItem_Call) RunAndReturn(run func(context.Context, string, string) (db.Item, error)) *MockStorage_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, username
func (_m *MockStorage) GetUser(ctx context.Context, username string) (string, string, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStorage_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStorage_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockStorage_Expecter) GetUser(ctx interface{}, username interface{}) *MockStorage_GetUser_Call {
	return &MockStorage_GetUser_Call{Call: _e.mock.On("GetUser", ctx, username)}
}

func (_c *MockStorage_GetUser_Call) Run(run func(ctx context.Context, username string)) *MockStorage_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetUser_Call) Return(_a0 string, _a1 string, _a2 error) *MockStorage_GetUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStorage_GetUser_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *MockStorage_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, userID, itemID, itemType, itemData, timestamp
func (_m *MockStorage) UpdateItem(ctx context.Context, userID string, itemID string, itemType int32, itemData []byte, timestamp time.Time) (db.Item, error) {
	ret := _m.Called(ctx, userID, itemID, itemType, itemData, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, []byte, time.Time) (db.Item, error)); ok {
		return rf(ctx, userID, itemID, itemType, itemData, timestamp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, []byte, time.Time) db.Item); ok {
		r0 = rf(ctx, userID, itemID, itemType, itemData, timestamp)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int32, []byte, time.Time) error); ok {
		r1 = rf(ctx, userID, itemID, itemType, itemData, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockStorage_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemID string
//   - itemType int32
//   - itemData []byte
//   - timestamp time.Time
func (_e *MockStorage_Expecter) UpdateItem(ctx interface{}, userID interface{}, itemID interface{}, itemType interface{}, itemData interface{}, timestamp interface{}) *MockStorage_UpdateItem_Call {
	return &MockStorage_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, userID, itemID, itemType, itemData, timestamp)}
}

func (_c *MockStorage_UpdateItem_Call) Run(run func(ctx context.Context, userID string, itemID string, itemType int32, itemData []byte, timestamp time.Time)) *MockStorage_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int32), args[4].([]byte), args[5].(time.Time))
	})
	return _c
}

func (_c *MockStorage_UpdateItem_Call) Return(_a0 db.Item, _a1 error) *MockStorage_UpdateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateItem_Call) RunAndReturn(run func(context.Context, string, string, int32, []byte, time.Time) (db.Item, error)) *MockStorage_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
