name: passkeeper

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.24

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.8
        with:
          repository: passkeeper/passkeeper
          latest: true
          fileName: "*"
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup passkeeper binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/passkeepertest /usr/local/bin/passkeepertest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Prepare binaries
        run: |
          go build -buildvcs=false -o cmd/server/passkeeper-server ./cmd/server

      - name: Test
        run: |
          passkeepertest \
            -test.v -test.run=^TestPasskeeper$ \
            -passkeeper-binary-path=cmd/server/passkeeper-server \
            -passkeeper-host=localhost \
            -passkeeper-port=50051 \
            -passkeeper-database-uri="postgresql://postgres:postgres@postgres/postgres?sslmode=disable"
