// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, username, password
func (_m *MockAuthService) CreateUser(ctx context.Context, username string, password string) error {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthService_Expecter) CreateUser(ctx interface{}, username interface{}, password interface{}) *MockAuthService_CreateUser_Call {
	return &MockAuthService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, password)}
}

func (_c *MockAuthService_CreateUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_CreateUser_Call) Return(_a0 error) *MockAuthService_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function with given fields: ctx, username, password
func (_m *MockAuthService) LoginUser(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockAuthService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthService_Expecter) LoginUser(ctx interface{}, username interface{}, password interface{}) *MockAuthService_LoginUser_Call {
	return &MockAuthService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, username, password)}
}

func (_c *MockAuthService_LoginUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_LoginUser_Call) Return(_a0 string, _a1 error) *MockAuthService_LoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_LoginUser_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAuthService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
