// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	db "passKeper/internal/repository/db"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockItemService is an autogenerated mock type for the ItemService type
type MockItemService struct {
	mock.Mock
}

type MockItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemService) EXPECT() *MockItemService_Expecter {
	return &MockItemService_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, itemType, itemData
func (_m *MockItemService) CreateItem(ctx context.Context, itemType int32, itemData []byte) (db.Item, error) {
	ret := _m.Called(ctx, itemType, itemData)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []byte) (db.Item, error)); ok {
		return rf(ctx, itemType, itemData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, []byte) db.Item); ok {
		r0 = rf(ctx, itemType, itemData)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, []byte) error); ok {
		r1 = rf(ctx, itemType, itemData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockItemService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType int32
//   - itemData []byte
func (_e *MockItemService_Expecter) CreateItem(ctx interface{}, itemType interface{}, itemData interface{}) *MockItemService_CreateItem_Call {
	return &MockItemService_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, itemType, itemData)}
}

func (_c *MockItemService_CreateItem_Call) Run(run func(ctx context.Context, itemType int32, itemData []byte)) *MockItemService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].([]byte))
	})
	return _c
}

func (_c *MockItemService_CreateItem_Call) Return(_a0 db.Item, _a1 error) *MockItemService_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemService_CreateItem_Call) RunAndReturn(run func(context.Context, int32, []byte) (db.Item, error)) *MockItemService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, itemID
func (_m *MockItemService) DeleteItem(ctx context.Context, itemID string) error {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemService_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockItemService_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
func (_e *MockItemService_Expecter) DeleteItem(ctx interface{}, itemID interface{}) *MockItemService_DeleteItem_Call {
	return &MockItemService_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, itemID)}
}

func (_c *MockItemService_DeleteItem_Call) Run(run func(ctx context.Context, itemID string)) *MockItemService_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockItemService_DeleteItem_Call) Return(_a0 error) *MockItemService_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemService_DeleteItem_Call) RunAndReturn(run func(context.Context, string) error) *MockItemService_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function with given fields: ctx, itemType
func (_m *MockItemService) GetAllItems(ctx context.Context, itemType int32) ([]db.Item, error) {
	ret := _m.Called(ctx, itemType)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Item, error)); ok {
		return rf(ctx, itemType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Item); ok {
		r0 = rf(ctx, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, itemType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemService_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockItemService_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType int32
func (_e *MockItemService_Expecter) GetAllItems(ctx interface{}, itemType interface{}) *MockItemService_GetAllItems_Call {
	return &MockItemService_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx, itemType)}
}

func (_c *MockItemService_GetAllItems_Call) Run(run func(ctx context.Context, itemType int32)) *MockItemService_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockItemService_GetAllItems_Call) Return(_a0 []db.Item, _a1 error) *MockItemService_GetAllItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemService_GetAllItems_Call) RunAndReturn(run func(context.Context, int32) ([]db.Item, error)) *MockItemService_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, id
func (_m *MockItemService) GetItem(ctx context.Context, id string) (db.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Item); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemService_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockItemService_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockItemService_Expecter) GetItem(ctx interface{}, id interface{}) *MockItemService_GetItem_Call {
	return &MockItemService_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockItemService_GetItem_Call) Run(run func(ctx context.Context, id string)) *MockItemService_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockItemService_GetItem_Call) Return(_a0 db.Item, _a1 error) *MockItemService_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemService_GetItem_Call) RunAndReturn(run func(context.Context, string) (db.Item, error)) *MockItemService_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, itemID, itemType, itemData, timestamp
func (_m *MockItemService) UpdateItem(ctx context.Context, itemID string, itemType int32, itemData []byte, timestamp time.Time) (db.Item, error) {
	ret := _m.Called(ctx, itemID, itemType, itemData, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, []byte, time.Time) (db.Item, error)); ok {
		return rf(ctx, itemID, itemType, itemData, timestamp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, []byte, time.Time) db.Item); ok {
		r0 = rf(ctx, itemID, itemType, itemData, timestamp)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, []byte, time.Time) error); ok {
		r1 = rf(ctx, itemID, itemType, itemData, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemService_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockItemService_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
//   - itemType int32
//   - itemData []byte
//   - timestamp time.Time
func (_e *MockItemService_Expecter) UpdateItem(ctx interface{}, itemID interface{}, itemType interface{}, itemData interface{}, timestamp interface{}) *MockItemService_UpdateItem_Call {
	return &MockItemService_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, itemID, itemType, itemData, timestamp)}
}

func (_c *MockItemService_UpdateItem_Call) Run(run func(ctx context.Context, itemID string, itemType int32, itemData []byte, timestamp time.Time)) *MockItemService_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].([]byte), args[4].(time.Time))
	})
	return _c
}

func (_c *MockItemService_UpdateItem_Call) Return(_a0 db.Item, _a1 error) *MockItemService_UpdateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemService_UpdateItem_Call) RunAndReturn(run func(context.Context, string, int32, []byte, time.Time) (db.Item, error)) *MockItemService_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemService creates a new instance of MockItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemService {
	mock := &MockItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
